### ISSUE TITLE
1.0.0 Launch Checklist

### ISSUE THREAD

**Issue by shshaw** [shshaw/Splitting#12]
- [x] Docs
- [ ] Examples
- [x] Favicon
- [ ] Deeper Browser Testing
- [x] Close out issues
- [x] Update README
- [x] Make sure references to 1.0.0 branch move to master
